name: CI - Build & Test

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]

  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build JAR (skip tests)
        run: mvn clean package -DskipTests=true
        working-directory: ./api

  tests:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run Tests
        run: mvn clean install
        working-directory: ./api

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Deploy API on Render
        run: |
          curl --request POST \
               --url https://api.render.com/v1/services/srv-d3nkkn1gv73c73cdjjng/deploys \
               --header 'accept: application/json' \
               --header "authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
               --header 'content-type: application/json' \
               --data '{"clearCache":"do_not_clear"}'